# Generated by Django 5.2.5 on 2025-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_job_currency_job_job_type_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_opens',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cgpa_requirement',
            field=models.CharField(blank=True, default='Not specified', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='key_responsibilities',
            field=models.TextField(blank=True, help_text='List the primary duties and responsibilities.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='minimum_qualifications',
            field=models.TextField(blank=True, help_text='List the essential qualifications and skills.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recommendation',
            field=models.TextField(blank=True, help_text='A short recommendation or highlight for the job.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Django, SQL)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='A general overview of the job and company.', null=True),
        ),
    ]
