# Generated by Django 5.2.5 on 2025-08-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_job_application_opens_job_cgpa_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.resume'),
        ),
    ]
